# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taller La Paz
email: lapazfineart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Somos especialistas en impresión, enmarcado y exhibición de arte contemporáneo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tallerlapaz.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
